### ISSUE TITLE
Review #1 - Muy buena app! + no se define al no jugar.

### ISSUE THREAD

**Issue by FacundoEG** [facundoaguilar96/desafio-m5#1]
Hola Facu! como andas?

Te comento que estuve probando la app y funciona muy buen la jugabilidad, lo unico que tengo como para sugerirte que cambies, es que cuando no elegis ninguna jugada, se queda trabado el contador y no te deja continuar:

![Screenshot_20220223_105354](https://user-images.githubusercontent.com/79592789/155333175-205d4262-31db-4f31-b643-6ccde7dc63af.png)

Te tendría que pedir que resuelvas esto ya que al pasar, estaría trabando el desarrollo del juego y el usuario no sabría que hacer si llegase hasta esa parte, podrías hacer que vuelva a la parte de instrucciones y listo.

Cualquier cosita si necesitas una ayuda avisame si?

Saludos!

**Comment by facundoaguilar96** [comment]
Hola Facu, todo bien. Tenía comentada la linea que vacía en currentPlay para que si no hay respuesta del usuario tome la jugada vacía y te vuelva a /rules, la abre comentado al buscar solución a otro problema y me olvidé de descomentarla.

**Comment by FacundoEG** [comment]
Listo Facu! Probé todo y anda de 10 ahora.

Te cierro el issue y aprobado el desafío 💪🏻

Éxitos en el próximo módulo!
